# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mM2CY9mG5Qvzb_egRjwPfzfPCTT24ga_

Task : Find relationship between Petrol consumption vs multiple factors
input : multiple factors with Petrol consuption
out put : Pertol consuption
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/w1_petrol_consumption.csv')

df.head(5)

df.describe().T.round(2)

from pandas._libs.tslibs.offsets import Hour
from matplotlib import pyplot as plt
plt.figure(figsize = (6,4))
plt.plot(df['Petrol_tax'],df['Petrol_Consumption'],'ro')
plt.title('Petrol Tax vs Consuption')
plt.xlabel('Petrol Tax')
plt.ylabel('Consuption')

plt.show()

from pandas._libs.tslibs.offsets import Hour
from matplotlib import pyplot as plt
plt.figure(figsize = (6,4))
plt.plot(df['Average_income'],df['Petrol_Consumption'],'ro')
plt.title('Average_income vs Consuption')
plt.xlabel('Average_income')
plt.ylabel('Consuption')

plt.show()

"""Train The Model"""

y = df['Petrol_Consumption'] #label output
x = df[['Average_income','Paved_Highways','Population_Driver_licence(%)','Petrol_tax']] #label inputs

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split (x, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(x_train,y_train)

regressor.intercept_

regressor.coef_

"""Make Predictions

"""

y_pred = regressor.predict(x_test)

results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(results)

"""Evalutating the Model"""

from sklearn.metrics import mean_absolute_error, mean_squared_error
MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test,y_pred)
RMSE = np.sqrt(MSE)

print(f'Mean Absolute Error {MAE:.3f}')
print(f'Mean Squred Error {MSE:.3f}')
print(f'Root Mean Squred Error {RMSE:.3f}')

regressor.score(x_test,y_test)

regressor.score(x_train,y_train)

