# -*- coding: utf-8 -*-
"""Project 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8FkSOCWG3EHoWIbcO_FGSBjRFMOcibi
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

data = pd.read_csv('/content/w2_position_salaries.csv')

data.head()

X = data["Level"].values.reshape(-1, 1)
y = data["Salary"].values

model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)

r2 = r2_score(y, y_pred)
print("R2 Score:", r2)

from sklearn.preprocessing import PolynomialFeatures

r2_scores = []

# Train polynomial regression models with degrees 2, 3, and 4
for degree in [2, 3, 4]:
    # Create polynomial features
    poly = PolynomialFeatures(degree=degree)
    X_poly = poly.fit_transform(X)

    # Create and fit the polynomial regression model
    model = LinearRegression()
    model.fit(X_poly, y)

    # Make predictions using the trained model
    y_pred = model.predict(X_poly)

    # Calculate the R2 score
    r2 = r2_score(y, y_pred)
    r2_scores.append((degree, r2))

# Print R2 scores for each degree
for degree, r2 in r2_scores:
    print(f"Degree {degree}: R2 Score = {r2:.4f}")









